"""adiciona google_id e name, e torna password opcional

Revision ID: 22454547edbf
Revises: 0ce27e92c507
Create Date: 2026-09-24 00:05:26.543366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22454547edbf'
down_revision = '0ce27e92c507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('name')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
